### ISSUE TITLE
Keyring fails

### ISSUE THREAD

**Issue by djmitche** [mozilla/inv-tool#12]
```
(moz)dustin@euclid ~/code/moz/t/invtool [more-config*] $ invtool search -q releng-puppet
Can't retrieve ldap password from keyring 'invtool-ldap'
ldap username: foo@mozilla.com
password:
Please input your password for the keyring
Password:
Traceback (most recent call last):
  File "/home/dustin/code/moz/bin/invtool", line 7, in <module>
    execfile(__file__)
  File "/home/dustin/code/moz/t/invtool/bin/invtool", line 6, in <module>
    sys.exit(main(sys.argv))
  File "/home/dustin/code/moz/t/invtool/invtool/main.py", line 53, in main
    resp_code, resp_list = dispatch(nas)
  File "/home/dustin/code/moz/t/invtool/invtool/dispatch.py", line 205, in dispatch
    return dispatch.route(nas)
  File "/home/dustin/code/moz/t/invtool/invtool/search_dispatch.py", line 42, in route
    return getattr(self, nas.dtype)(nas)
  File "/home/dustin/code/moz/t/invtool/invtool/search_dispatch.py", line 50, in search
    return self.query(nas)
  File "/home/dustin/code/moz/t/invtool/invtool/search_dispatch.py", line 98, in query
    resp = requests.get(url, params=search, headers=headers, auth=auth())
  File "/home/dustin/code/moz/t/invtool/invtool/lib/config.py", line 131, in auth
    authcache = _realauth()
  File "/home/dustin/code/moz/t/invtool/invtool/lib/config.py", line 64, in _keyring
    auth[1]
  File "/home/dustin/code/moz/lib/python2.7/site-packages/keyring/core.py", line 35, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/home/dustin/code/moz/lib/python2.7/site-packages/keyring/backend.py", line 277, in set_password
    password_encrypted = self.encrypt(password)
  File "/home/dustin/code/moz/lib/python2.7/site-packages/keyring/backend.py", line 423, in encrypt
    crypter = self._init_crypter()
  File "/home/dustin/code/moz/lib/python2.7/site-packages/keyring/backend.py", line 418, in _init_crypter
    return AES.new(password, AES.MODE_CFB)
  File "/usr/lib/python2.7/site-packages/Crypto/Cipher/AES.py", line 95, in new
    return AESCipher(key, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/Crypto/Cipher/AES.py", line 59, in __init__
    blockalgo.BlockAlgo.__init__(self, _AES, key, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
ValueError: IV must be 16 bytes long
```

I didn't give it an IV, so I'm not sure what to do with that.

**Comment by uberj** [comment]
Me neither. Can you reproduce the error?

**Comment by djmitche** [comment]
Yes - I wonder if it's a different version of keychain or some dependency?  I'll admit I didn't google for it!  We can debug next week.

**Comment by djmitche** [comment]
I was using an old version of pycrypto.  `pip install -U` to the rescue!
