### ISSUE TITLE
"invtool search" without any arguments emits TypeError: 'NoneType'

### ISSUE THREAD

**Issue by floatingatoll** [mozilla/inv-tool#7]
While learning my way around, I found an unhandled exception for search without arguments.

```
$ ./devinvtool search
Traceback (most recent call last):
  File "./devinvtool", line 6, in <module>
    sys.exit(main(sys.argv))
  File "/Users/coral/inv-tool/invtool/main.py", line 32, in main
    resp_code, resp_list = dispatch(nas)
TypeError: 'NoneType' object is not iterable
```

Status says I'm connected, if that's of any help.

```
$ ./devinvtool status
Status Vars
AUTH_TYPE: keyring
CONFIG_FILE: ./etc/invtool.conf
GLOBAL_CONFIG_FILE: /etc/invtool.conf
LOCAL_CONFIG_FILE: ./etc/invtool.conf
dev: False
host: [redacted]
REMOTE: https://[redacted]:443
API_MAJOR_VERSION: 1
port: 443
```

**Comment by uberj** [comment]
Nice find.

**Comment by uberj** [comment]
This is fixed
